### ISSUE TITLE
Jogo trava quando espaço vazio está no canto superior direito

### ISSUE THREAD

**Issue by teles** [rafa-ribeiro/game_of_fifteen#1]
![ezgif-6-a2df44ce7c51](https://user-images.githubusercontent.com/762639/77165475-21e9e400-6a91-11ea-8915-52dc745482e0.gif)

Estava jogando, cheguei no canto superior direito e não consegui mais mover as peças.
Não sei se ocorre nos outros cantos.

**Comment by rafa-ribeiro** [comment]
Muito obrigado, @teles!

O bug acontecia porque a estratégia que faço pra saber qual peça mover é descobri-la a partir do espaço vazio quando uma tecla é acionada. Em alguns casos, se o índice calculado era um valor fora dos limites da matriz, o jogo quebrava, causando o travamento. Adicionei essas validações agora. Obrigadão, Teles!!!
