### ISSUE TITLE
Corrigir o mostrador de movimentos do game.

### ISSUE THREAD

**Issue by rafa-ribeiro** [rafa-ribeiro/game_of_fifteen#21]
Problema:

- Atualmente o mostrador de movimentos realizados pelo jogador exibe corretamente para movimentos com 3 algarismos, no entanto, caso o jogador ultrapasse de 999 movimentos, o mostrador não é devidamente exibido, não mostrando os movimentos de forma completa.

Solução:

- Essa issue tem por objetivo corrigir essa funcionalidade, seja aumentando o valor da caixa de movimentos ou fazendo o texto se ajustar de acordo com a quantidade de algarismos contidos na caixa de texto.

**Comment by LivSith** [comment]
Me passa essa issue???
